In [1]:
import numpy as np

In [2]:
n1 = np.array([[5, 4, 3], [7, 8, 9]])

In [3]:
n1

array([[5, 4, 3],
       [7, 8, 9]])

In [4]:
m1 = np.array([[11, 12, 13], [14, 15, 16]])

In [5]:
m1

array([[11, 12, 13],
       [14, 15, 16]])

## Creating the tensor

In [8]:
tensor = np.array([n1, m1])

In [9]:
tensor

array([[[ 5,  4,  3],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [10]:
tensor.shape

(2, 2, 3)

## Creating tensor manually!

In [13]:
t_manual = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 12, 13], [14, 15, 16]]])

In [14]:
t_manual

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [15]:
t_manual.shape

(2, 2, 3)